import express from 'express';
import {fileURLToPath} from 'node:url';
import { MongoClient, ObjectId } from 'mongodb';
import { validateTrade } from './validation.js';
import {searchTradingView,resolveSymbol} from './tradingview.js';
const app = express();
app.use(express.json({limit:'100kb'}));
app.use((req,res,next)=>{if(req.method!=='GET' && req.headers.origin && req.headers.origin!==`http://${req.headers.host}`)return res.status(403).json({error:'İstek kaynağına izin verilmiyor.'});next();});
app.disable('x-powered-by');
app.use(express.static(fileURLToPath(new URL('./public/',import.meta.url))));
if(!process.env.MONGODB_URI){console.error('MONGODB_URI bağlantı bilgisini .env dosyasına veya ortam değişkenlerine ekleyin.');process.exit(1);}
const client = new MongoClient(process.env.MONGODB_URI,{serverSelectionTimeoutMS:7000});
let db;
try { await client.connect(); db=client.db(process.env.MONGODB_DB || 'trade'); await db.collection('trades').createIndex({date:1}); await db.collection('journal').createIndex({updatedAt:-1}); if(!await db.collection('wallets').countDocuments({}))await db.collection('wallets').updateOne({_id:'main'},{$setOnInsert:{name:'Ana Cüzdan',createdAt:new Date()}},{upsert:true}); const defaultWallet=await db.collection('wallets').findOne({}, {sort:{createdAt:1}}); await db.collection('trades').updateMany({walletId:{$exists:false}},{$set:{walletId:defaultWallet._id}}); await db.collection('trades').createIndex({walletId:1,date:-1}); console.log('MongoDB bağlantısı hazır.'); }
catch { console.error('MongoDB bağlantısı kurulamadı. Bağlantı bilgilerini ve sunucu erişimini kontrol edin.'); process.exit(1); }
app.get('/api/market/coins',async(req,res,next)=>{try{res.json(await searchTradingView(req.query.q));}catch(e){next(e);}});
app.get('/api/wallets',async(req,res,next)=>{try{res.json(await db.collection('wallets').find({}).sort({createdAt:1}).toArray());}catch(e){next(e);}});
app.post('/api/wallets',async(req,res,next)=>{try{const name=req.body.name;if(typeof name!=='string'||!name.trim()||name.trim().length>60)return res.status(400).json({error:'Cüzdan adı 1–60 karakter olmalı.'});const wallet={_id:new ObjectId().toHexString(),name:name.trim(),createdAt:new Date()};await db.collection('wallets').insertOne(wallet);res.status(201).json(wallet);}catch(e){next(e);}});
app.delete('/api/wallets/:id',async(req,res,next)=>{try{if(req.body.confirmation!=='SİL')return res.status(400).json({error:'Silme onayı gerekli.'});const wallet=await db.collection('wallets').findOne({_id:req.params.id});if(!wallet)return res.status(404).json({error:'Cüzdan bulunamadı.'});if(await db.collection('wallets').countDocuments({})<=1)return res.status(400).json({error:'Son cüzdan silinemez. Önce başka bir cüzdan oluşturun.'});await db.collection('trades').deleteMany({walletId:wallet._id});await db.collection('wallets').deleteOne({_id:wallet._id});res.json({ok:true});}catch(e){next(e);}});
app.use('/api/trades',async(req,res,next)=>{try{const id=req.query.walletId||'main';if(typeof id!=='string'||!await db.collection('wallets').findOne({_id:id}))return res.status(400).json({error:'Geçerli bir cüzdan seçin.'});req.walletId=id;next();}catch(e){next(e);}});
app.delete('/api/trades',async(req,res,next)=>{try{if(req.body.confirmation!=='SİL')return res.status(400).json({error:'Silme onayı gerekli.'});const r=await db.collection('trades').deleteMany({walletId:req.walletId});res.json({deletedCount:r.deletedCount});}catch(e){next(e);}});
app.get('/api/trades',async(req,res,next)=>{try{res.json(await db.collection('trades').find({walletId:req.walletId}).sort({date:-1,createdAt:-1}).toArray());}catch(e){next(e);}});
app.post('/api/trades',async(req,res,next)=>{try{const trade=validateTrade(req.body);const market=await resolveSymbol(trade.symbol);if(market){trade.image=market.image;trade.market=market.source;trade.exchange=market.exchange;}const result=await db.collection('trades').insertOne({...trade,walletId:req.walletId,createdAt:new Date()});res.status(201).json({...trade,_id:result.insertedId});}catch(e){next(e);}});
app.put('/api/trades/:id',async(req,res,next)=>{try{if(!/^[a-f\d]{24}$/i.test(req.params.id))return res.status(400).json({error:'Geçersiz işlem.'});const trade=validateTrade(req.body);const result=await db.collection('trades').updateOne({_id:new ObjectId(req.params.id),walletId:req.walletId},{$set:trade});if(!result.matchedCount)return res.status(404).json({error:'İşlem bulunamadı.'});res.json(trade);}catch(e){next(e);}});
app.delete('/api/trades/:id',async(req,res,next)=>{try{if(!/^[a-f\d]{24}$/i.test(req.params.id))return res.status(400).json({error:'Geçersiz işlem.'});const r=await db.collection('trades').deleteOne({_id:new ObjectId(req.params.id),walletId:req.walletId});if(!r.deletedCount)return res.status(404).json({error:'İşlem bulunamadı.'});res.json({ok:true});}catch(e){next(e);}});
const noteId=id=>/^(?:[a-f\d]{24}|\d{4}-\d{2}-\d{2})$/i.test(id);
const noteBody=body=>{if(typeof body.title!=='string'||!body.title.trim()||body.title.length>120||typeof body.text!=='string'||body.text.length>20000){const e=new Error('Not başlığı ve içeriğini kontrol edin.');e.status=400;throw e;}return {title:body.title.trim(),text:body.text};};
app.get('/api/notes',async(req,res,next)=>{try{res.json(await db.collection('journal').find({deletedAt:{$exists:false},$or:[{title:{$exists:true}},{text:{$nin:['',null]}}]}).sort({updatedAt:-1}).toArray());}catch(e){next(e);}});
app.post('/api/notes',async(req,res,next)=>{try{const note={...noteBody(req.body),_id:new ObjectId().toHexString(),createdAt:new Date(),updatedAt:new Date()};await db.collection('journal').insertOne(note);res.status(201).json(note);}catch(e){next(e);}});
app.put('/api/notes/:id',async(req,res,next)=>{try{if(!noteId(req.params.id))return res.status(400).json({error:'Geçersiz not.'});const result=await db.collection('journal').updateOne({_id:req.params.id,deletedAt:{$exists:false}},{$set:{...noteBody(req.body),updatedAt:new Date()}});if(!result.matchedCount)return res.status(404).json({error:'Not bulunamadı.'});res.json({ok:true});}catch(e){next(e);}});
app.delete('/api/notes/:id',async(req,res,next)=>{try{if(!noteId(req.params.id))return res.status(400).json({error:'Geçersiz not.'});const result=await db.collection('journal').updateOne({_id:req.params.id},{$set:{deletedAt:new Date()}});if(!result.matchedCount)return res.status(404).json({error:'Not bulunamadı.'});res.json({ok:true});}catch(e){next(e);}});
app.get('/api/journal/:date',async(req,res,next)=>{try{res.json(await db.collection('journal').findOne({_id:req.params.date})||{text:''});}catch(e){next(e);}});
app.put('/api/journal/:date',async(req,res,next)=>{try{if(!/^\d{4}-\d{2}-\d{2}$/.test(req.params.date)||typeof req.body.text!=='string'||req.body.text.length>20000)return res.status(400).json({error:'Geçersiz günlük notu.'});await db.collection('journal').updateOne({_id:req.params.date},{$set:{text:req.body.text,updatedAt:new Date()}},{upsert:true});res.json({ok:true});}catch(e){next(e);}});
app.use((err,req,res,next)=>res.status(err.status||500).json({error:err.status?err.message:'İşlem tamamlanamadı. Lütfen tekrar deneyin.'}));
const server=app.listen(process.env.PORT||3000,'127.0.0.1',()=>console.log('Panel: http://localhost:'+(process.env.PORT||3000)));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{server.close(async()=>{await client.close();process.exit(0);});setTimeout(()=>process.exit(1),10000).unref();});
